/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/sso/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["startBrowserLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sso/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["finishBrowserLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logoutBrowserSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIdentityProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connectors/claude-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getClaudeCodeConnection"];
        /** @deprecated */
        put: operations["connectClaudeCodeWithCredential"];
        post?: never;
        delete: operations["disconnectClaudeCode"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connectors/claude-code/oauth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startClaudeCodeOAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connectors/claude-code/oauth/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeClaudeCodeOAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listConnections"];
        put?: never;
        post: operations["startConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connect-sessions/{connect_session_ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConnectSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capability-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCapabilityProfiles"];
        put?: never;
        post: operations["createCapabilityProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capability-profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateCapabilityProfile"];
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAgents"];
        put?: never;
        post: operations["createManagedAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitAgentTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["streamTaskEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/publications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMcpPublications"];
        put?: never;
        post: operations["publishCapabilityProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/publications/{publication_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMcpPublication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["changeMcpPublicationState"];
        trace?: never;
    };
    "/api/mcp/publications/{publication_id}/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMcpClientAuthorizations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/publications/{publication_id}/clients/{authorization_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeMcpClientAuthorization"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/publications/{publication_id}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMcpApprovals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRepositories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["openRepositoryProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRepositoryProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjectBranches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjectTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/engineering-artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjectEngineeringArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/branch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["selectProjectBranch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjectThreads"];
        put?: never;
        post: operations["createProjectThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{thread_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listThreadMessages"];
        put?: never;
        post: operations["createThreadMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjectWorkflows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/workflow-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startProjectWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["openapi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/oauth-protected-resource": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["mcpRootProtectedResourceMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/oauth-protected-resource/mcp/{publication_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["mcpProtectedResourceMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/{publication_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mcp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            code: string;
        };
        Session: {
            tenant_id: string;
            subject: string;
            email?: string | null;
            groups: string[];
        };
        IdentityProvider: {
            id: string;
            display_name: string;
        };
        /** @enum {string} */
        PublicationState: "active" | "suspended" | "revoked";
        Publication: {
            publication_id: string;
            tenant_id: string;
            owner_subject: string;
            profile_id: string;
            active_revision: number;
            toolset_digest: string;
            state: components["schemas"]["PublicationState"];
            created_at_ms: number;
            updated_at_ms: number;
        };
        ClientAuthorization: {
            authorization_id: string;
            publication_id: string;
            subject: string;
            client_id: string;
            display_name: string;
            /** @enum {string} */
            state: "active" | "revoked";
            first_used_at_ms: number;
            last_used_at_ms: number;
        };
        Approval: {
            approval_id: string;
            publication_id: string;
            authorization_id: string;
            subject: string;
            client_id: string;
            tool_name: string;
            operation_ref: string;
            connection_id: string;
            input_digest: string;
            /** @enum {string} */
            state: "pending" | "approved" | "denied" | "consumed" | "expired" | "outcome_unknown";
            expires_at_ms: number;
            audit_ref?: string | null;
            created_at_ms: number;
            updated_at_ms: number;
        };
        ConnectionStatus: {
            /** @constant */
            provider: "claude-code";
            connected: boolean;
        };
        ConnectClaudeCode: {
            /** Format: password */
            credential: string;
        };
        ClaudeOAuthStart: {
            /** Format: uri */
            authorization_url: string;
            flow_id: string;
            expires_at: number;
        };
        CompleteClaudeOAuth: {
            flow_id: string;
            /** Format: password */
            code: string;
        };
        StartConnection: {
            integration_ref: string;
            label: string;
            auth_profile?: string | null;
        };
        ConnectSession: {
            connect_session_ref: string;
            integration_ref: string;
            /** @enum {string} */
            state: "pending" | "completed" | "expired" | "failed";
            expires_at_unix_ms: number;
            completion_endpoint?: string | null;
            /** Format: uri */
            browser_completion_url?: string | null;
            connection_ref?: string | null;
        };
        ConnectorConnection: {
            connection_ref: string;
            integration_ref: string;
            label: string;
            /** @enum {string} */
            state: "created" | "authorized" | "callable" | "degraded" | "revoked";
            initiation: ("b10x" | "provider")[];
            route: Record<string, never>;
            /** @enum {string|null} */
            scope?: "tenant" | "principal" | null;
            /** @enum {string|null} */
            actor?: "app" | "user" | null;
            auth_profile?: string | null;
        };
        CapabilityConnection: {
            connection_ref: string;
            label: string;
            provider: string;
            audiences: string[];
            purpose?: string | null;
        };
        Capability: {
            operation_ref: string;
            title: string;
            /** @enum {string} */
            effect: "read_only" | "mutating" | "destructive";
            /** @enum {string} */
            approval: "not_required" | "required";
            connections: components["schemas"]["CapabilityConnection"][];
        };
        CapabilityMapping: {
            operation_ref: string;
            tool_name: string;
            connection_ref?: string | null;
            context?: string | null;
            /** @enum {string} */
            posture: "allow" | "approval_required" | "deny";
        };
        CreateCapabilityProfile: {
            name: string;
            mappings: components["schemas"]["CapabilityMapping"][];
        };
        UpdateCapabilityProfile: {
            expected_revision: number;
            name: string;
            mappings: components["schemas"]["CapabilityMapping"][];
        };
        CapabilityProfile: {
            id: string;
            tenant_id: string;
            name: string;
            revision: number;
            mappings: components["schemas"]["CapabilityMapping"][];
            compiled: Record<string, never>;
            created_by: string;
            created_at_ms: number;
            updated_at_ms: number;
        };
        RepositoryCandidate: {
            forge_instance_ref: string;
            project_ref: string;
            path_with_namespace: string;
            name: string;
            default_branch?: string | null;
            visibility: string;
            web_url: string;
            opened_project_id?: string | null;
        };
        OpenProject: {
            forge_instance_ref: string;
            project_ref: string;
        };
        Project: {
            id: string;
            forge_instance_ref: string;
            project_ref: string;
            path_with_namespace: string;
            name: string;
            default_branch?: string | null;
            selected_branch: string;
            pinned_commit?: string | null;
            web_url: string;
        };
        Branch: {
            name: string;
            commit: string;
            provider_default: boolean;
            protected: boolean;
        };
        RepositoryEntry: {
            object_id: string;
            name: string;
            path: string;
            /** @enum {string} */
            kind: "blob" | "tree";
            mode: string;
        };
        EngineeringArtifact: {
            id: string;
            locator: string;
            entity_type: string;
            revision: number;
            title?: string | null;
            status?: string | null;
            updated_at_ms: number;
            source_revision?: string | null;
        };
        EngineeringArtifactPage: {
            artifacts: components["schemas"]["EngineeringArtifact"][];
            has_more: boolean;
        };
        SelectBranch: {
            branch: string;
        };
        ProjectThread: {
            id: string;
            project_id: string;
            branch: string;
            pinned_commit: string;
            title: string;
            created_at_ms: number;
        };
        CreateProjectThread: {
            branch: string;
            pinned_commit: string;
            title: string;
        };
        ProjectMessage: {
            sequence: number;
            /** @enum {string} */
            role: "user" | "assistant" | "system";
            content: string;
            branch: string;
            commit: string;
            created_at_ms: number;
        };
        CreateProjectMessage: {
            content: string;
        };
        WorkflowDefinition: {
            id: string;
            name: string;
            description: string;
        };
        StartWorkflow: {
            definition_id: string;
            branch: string;
            commit: string;
            idempotency_key: string;
        };
        WorkflowRun: {
            id: string;
            definition_id: string;
            project_id: string;
            branch: string;
            commit: string;
            /** @enum {string} */
            state: "accepted" | "running" | "succeeded" | "failed" | "refused";
            failure_code?: string | null;
            created_at_ms: number;
        };
        CreateAgent: {
            name: string;
            instructions: string;
            model: string;
            /** @description Existing immutable capability profile assigned to the first agent revision */
            capability_profile_id?: string;
        };
        Agent: {
            id: string;
            tenant_id: string;
            name: string;
            active_revision?: number | null;
            latest_revision: number;
            created_by: string;
            created_at_ms: number;
        };
        SubmitTask: {
            prompt: string;
            idempotency_key: string;
        };
        Task: {
            id: string;
            agent_id: string;
            status: string;
            attempt_id: string;
            output?: string | null;
        };
    };
    responses: {
        /** @description Request refused */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description A required inner service is unavailable */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        AgentId: string;
        TaskId: string;
        PublicationId: string;
        ProjectId: string;
        ThreadId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    startBrowserLogin: {
        parameters: {
            query?: {
                /** @description Opaque configured Identity provider ID */
                provider?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the configured identity provider */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            503: components["responses"]["Unavailable"];
        };
    };
    finishBrowserLogin: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
                error?: string;
                error_description?: string;
                error_uri?: string;
                iss?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Opaque browser session established */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
        };
    };
    logoutBrowserSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Browser session cookie cleared; persistent MCP authorizations are unchanged */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
        };
    };
    listIdentityProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deployment-configured provider choices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityProvider"][];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current principal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    getClaudeCodeConnection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionStatus"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    connectClaudeCodeWithCredential: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectClaudeCode"];
            };
        };
        responses: {
            /** @description Compatibility credential accepted into connector custody */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionStatus"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    disconnectClaudeCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    startClaudeCodeOAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded provider authorization step */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaudeOAuthStart"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            503: components["responses"]["Unavailable"];
        };
    };
    completeClaudeCodeOAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteClaudeOAuth"];
            };
        };
        responses: {
            /** @description Provider credentials accepted into connector custody */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionStatus"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Unavailable"];
        };
    };
    listConnections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connections visible through the current Connector grants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorConnection"][];
                };
            };
            401: components["responses"]["Problem"];
            503: components["responses"]["Unavailable"];
        };
    };
    startConnection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartConnection"];
            };
        };
        responses: {
            /** @description Connector-owned acquisition session */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectSession"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            503: components["responses"]["Unavailable"];
        };
    };
    getConnectSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connect_session_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current Connector acquisition state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectSession"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            503: components["responses"]["Unavailable"];
        };
    };
    listCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Callable operations under current Connector grants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capability"][];
                };
            };
            401: components["responses"]["Problem"];
            503: components["responses"]["Unavailable"];
        };
    };
    listCapabilityProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revisioned Agent Platform capability profiles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityProfile"][];
                };
            };
            401: components["responses"]["Problem"];
            503: components["responses"]["Unavailable"];
        };
    };
    createCapabilityProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCapabilityProfile"];
            };
        };
        responses: {
            /** @description Profile compiled from current credential-free Connector descriptions */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityProfile"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Unavailable"];
        };
    };
    updateCapabilityProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCapabilityProfile"];
            };
        };
        responses: {
            /** @description New compare-and-swap profile revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityProfile"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Unavailable"];
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant-scoped agents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"][];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    createManagedAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAgent"];
            };
        };
        responses: {
            /** @description Agent created with an active first revision */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    submitAgentTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitTask"];
            };
        };
        responses: {
            /** @description Task accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    streamTaskEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered, attempt-bound task event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    listMcpPublications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Publications owned by the stable internal subject */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Publication"][];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    publishCapabilityProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    profile_id: string;
                };
            };
        };
        responses: {
            /** @description Immutable profile revision published */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Publication"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    getMcpPublication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publication_id: components["parameters"]["PublicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owned publication */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Publication"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    changeMcpPublicationState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publication_id: components["parameters"]["PublicationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    state: components["schemas"]["PublicationState"];
                };
            };
        };
        responses: {
            /** @description Publication state changed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Publication"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    listMcpClientAuthorizations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publication_id: components["parameters"]["PublicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Credential-free OAuth client authorizations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientAuthorization"][];
                };
            };
        };
    };
    revokeMcpClientAuthorization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publication_id: components["parameters"]["PublicationId"];
                authorization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One client authorization revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["Unavailable"];
        };
    };
    listMcpApprovals: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publication_id: components["parameters"]["PublicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending exact-input approvals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"][];
                };
            };
        };
    };
    listRepositories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repositories visible through current Connector Grants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryCandidate"][];
                };
            };
            401: components["responses"]["Problem"];
            503: components["responses"]["Unavailable"];
        };
    };
    openRepositoryProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenProject"];
            };
        };
        responses: {
            /** @description Canonical project opened after live revalidation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getRepositoryProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current accessible project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    listProjectBranches: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Currently visible branch heads */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"][];
                };
            };
            403: components["responses"]["Problem"];
        };
    };
    listProjectTree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Read-only root entries at the exact pinned commit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryEntry"][];
                };
            };
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    listProjectEngineeringArtifacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded central AEP entities indexed to this project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineeringArtifactPage"];
                };
            };
            403: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    selectProjectBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectBranch"];
            };
        };
        responses: {
            /** @description Explicitly refreshed project snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    listProjectThreads: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Personal project threads */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectThread"][];
                };
            };
        };
    };
    createProjectThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectThread"];
            };
        };
        responses: {
            /** @description Personal branch-bound thread */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectThread"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    listThreadMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Personal durable messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMessage"][];
                };
            };
        };
    };
    createThreadMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectMessage"];
            };
        };
        responses: {
            /** @description Commit-attributed user message */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMessage"];
                };
            };
        };
    };
    listProjectWorkflows: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enabled immutable workflow definitions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinition"][];
                };
            };
        };
    };
    startProjectWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartWorkflow"];
            };
        };
        responses: {
            /** @description Exact-snapshot workflow run admitted idempotently */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRun"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Required service clients are configured */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Configuration is incomplete */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    openapi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mcpRootProtectedResourceMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RFC 9728 metadata for the Devcenter MCP resource root */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mcpProtectedResourceMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publication_id: components["parameters"]["PublicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RFC 9728 metadata for the exact publication resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed publication ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mcp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publication_id: components["parameters"]["PublicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description MCP Streamable HTTP JSON-RPC response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description MCP notification accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
}
