{{- if (index .Values.components "connectors").enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devcenter.fullname" . }}-connectors
  labels:
    {{- include "devcenter.labels" . | nindent 4 }}
    app.kubernetes.io/component: connectors
automountServiceAccountToken: true
{{- end }}
{{- if (index .Values.components "secrets").enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devcenter.fullname" . }}-secrets
  labels:
    {{- include "devcenter.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "devcenter.workloadName" . }}-secrets-tokenreview-{{ .Release.Namespace }}
  labels:
    {{- include "devcenter.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: {{ include "devcenter.fullname" . }}-secrets
    namespace: {{ .Release.Namespace }}
{{- end }}
