apiVersion: v1
kind: Service
metadata:
  name: {{ include "devcenter.fullname" . }}
  labels:
    {{- include "devcenter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "devcenter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: devcenter
  ports:
    - name: http
      port: {{ .Values.devcenter.service.port }}
      targetPort: http
