{{- if (index .Values.components "connectors").enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devcenter.fullname" . }}-connectors
  labels:
    {{- include "devcenter.labels" . | nindent 4 }}
    app.kubernetes.io/component: connectors
automountServiceAccountToken: true
{{- end }}
