{{- if and .Values.secretStore.vault.enabled .Values.secretStore.vault.tls.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-vault-selfsigned
  labels: {{- include "devcenter.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-vault-ca
  labels: {{- include "devcenter.labels" . | nindent 4 }}
spec:
  isCA: true
  commonName: {{ printf "%s internal Vault CA" .Release.Name | quote }}
  secretName: {{ .Release.Name }}-vault-ca
  duration: {{ .Values.secretStore.vault.tls.certManager.duration | quote }}
  renewBefore: {{ .Values.secretStore.vault.tls.certManager.renewBefore | quote }}
  privateKey: {algorithm: ECDSA, size: 256}
  issuerRef: {kind: Issuer, name: {{ .Release.Name }}-vault-selfsigned}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-vault-ca
  labels: {{- include "devcenter.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ .Release.Name }}-vault-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-vault-tls
  labels: {{- include "devcenter.labels" . | nindent 4 }}
spec:
  secretName: {{ .Release.Name }}-vault-tls
  duration: {{ .Values.secretStore.vault.tls.certManager.duration | quote }}
  renewBefore: {{ .Values.secretStore.vault.tls.certManager.renewBefore | quote }}
  privateKey: {algorithm: ECDSA, size: 256}
  usages: [server auth]
  dnsNames:
    - {{ .Release.Name }}-vault
    - {{ .Release.Name }}-vault.{{ .Release.Namespace }}
    - {{ .Release.Name }}-vault.{{ .Release.Namespace }}.svc
    - {{ .Release.Name }}-vault.{{ .Release.Namespace }}.svc.cluster.local
    - {{ .Release.Name }}-vault-active
    - {{ .Release.Name }}-vault-active.{{ .Release.Namespace }}.svc
    - {{ .Release.Name }}-vault-internal
    - {{ .Release.Name }}-vault-0.{{ .Release.Name }}-vault-internal
    - {{ .Release.Name }}-vault-0.{{ .Release.Name }}-vault-internal.{{ .Release.Namespace }}.svc
  issuerRef: {kind: Issuer, name: {{ .Release.Name }}-vault-ca}
{{- end }}
